services:
  app:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - functions

  functions:
    build: ./functions
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./functions:/usr/src/app
      - /usr/src/app/node_modules
